# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba71e5e23600c4d921dfcfeda2883250f94cb4f25643d3b228980a7d4a436287d6a487223ed807119178d227b764f0dac6a585d460548c75b71bbe6a0ffd1861

test:
  secret_key_base: 4b5659c6f6a4e94bba5e00e402c30b5c474b5652bf126ff8ebcaca1e91d45cf94d04f302c0ae36fa4099680ee50487fee6956ab05adcead22f871121fdfb806c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
